Repository LucasFournier-GIT/shoploc-backend, pull requests merged in 2023-12, with the labels that each got.

#16 ci: encore changement sur la github actions
  .github/workflows/maven.yml
Labels: 🚀 CI/CD

#20 ci: fix ci with false database
  shoplocBackend/pom.xml
  shoplocBackend/src/main/java/fr/shoploc/shoplocBackend/Application.java
  shoplocBackend/src/main/resources/application-ci.properties
  shoplocBackend/src/main/resources/application.properties
  shoplocBackend/src/test/java/fr/shoploc/shoplocBackend/ShoplocBackendApplicationTests.java
Labels: 👾 bug, 🚀 CI/CD

#22 test: add test to shop and product package
  shoplocBackend/pom.xml
  shoplocBackend/src/test/java/fr/shoploc/shoplocBackend/product/ProductRepositoryTests.java
  shoplocBackend/src/test/java/fr/shoploc/shoplocBackend/product/ProductTests.java
  shoplocBackend/src/test/java/fr/shoploc/shoplocBackend/shop/ShopTests.java
Labels: ✅ test

#29 feat: gestion des erreurs de connexion et diffusion de token - SCRUM-22
  shoplocFrontend/App.js
  shoplocFrontend/components/AuthContext.js
  shoplocFrontend/components/CustomModal.js
  shoplocFrontend/components/CustomNavBar.js
  shoplocFrontend/components/screens/CartScreen.js
  shoplocFrontend/components/screens/CreateAccountScreen.js
  shoplocFrontend/components/screens/HomeScreen.js
  shoplocFrontend/components/screens/LoginScreen.js
  shoplocFrontend/components/screens/PaymentScreen.js
  shoplocFrontend/components/screens/ShopScreen.js
Labels: 🛰️ feature

#23 fix: change version of semver due to security vulnerability
  shoplocFrontend/package-lock.json
Labels: 🛡 security

#30 fix : position of navbar RecapCartSceen and PaymentScreen - SCRUM-37
  shoplocFrontend/assets/logo.png
  shoplocFrontend/components/screens/PaymentScreen.js
  shoplocFrontend/components/screens/RecapCartScreen.js
Labels: 🛰️ feature

#32 fix: put deleteMapping for delete endpoint and fix route - SCRUM-35
  shoplocBackend/src/main/java/fr/shoploc/shoplocBackend/productInCart/controller/ProductInCartController.java
Labels: 👾 bug
